/* Criando o banco de dados */
CREATE DATABASE PROJETO;
/* Conectando ao banco */
USE PROJETO;
/* Criando a tabela  */
CREATE TABLE CLIENTE (
  NOME VARCHAR(30),
  SEXO CHAR(1),
  EMAIL VARCHAR(30),
  CPF INT(11),
  TELEFONE VARCHAR(30),
  ENDERECO VARCHAR(100)
);
/* VERFIFICANDO AS TABELAS */
SHOW TABLES;
/* DESCOBRINDO A ESTRUTURA DE UMA TABELA */
DESC CLIENTE;
