/* COMANDO SELECT */
/* SELEÇÃO - PROJEÇÃO - JUNÇÃO */
SELECT NOW();
SELECT NOW() AS DATA_HORA;
SELECT NOW() AS DATA_HORA, 'LEO SILVA' AS EXTRAORDINARIO;
SELECT 'LEO SILVA';
SELECT 'BANCO DE DADOS MYSQL';

/* ALIAS DE COLUNAS */
SELECT NOME, SEXO, EMAIL FROM CLIENTE;
SELECT NOME AS CLIENTE, SEXO, EMAIL FROM CLIENTE;
SELECT NOME, SEXO, EMAIL, ENDERECO FROM CLIENTE;
SELECT EMAIL, SEXO, ENDERECO, NOME FROM CLIENTE;
SELECT NOME, SEXO, EMAIL, ENDERECO, NOW() AS DATA_HORA FROM CLIENTE;
