version: '3.8'

services:
  mysql-db:
    image: mysql:latest
    container_name: my-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: db_aula
      MYSQL_USER: leo
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - ./dados_mysql:/var/lib/mysql
